version: '3.8'
services:
  postgres:
    image: postgres:17.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/postgresql/data